[package]
name = "rix-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords = ["nix", "cli"]

[dependencies]
clap.workspace = true
thiserror.workspace = true
rix-parser.workspace = true
rix-eval.workspace = true
serde_json.workspace = true
rootcause.workspace = true
