[package]
name = "rix-cli"
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/tinted-software/rix"
keywords = ["nix", "cli"]

[dependencies]
clap.workspace = true
thiserror.workspace = true
rix-parser.workspace = true
rix-eval.workspace = true
serde_json.workspace = true
rootcause.workspace = true
