[package]
name = "rix-parser"
description = "A Nix parser written in Rust"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bench]]
harness = false
name = "all-packages"

[dependencies]
rowan.workspace = true

[dev-dependencies]
criterion.workspace = true
expect-test.workspace = true
